export const Books = [
  {
    id: 1,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "fiction",
    condition: "Good",
    price: 150,
    type: "sell",
    description: "Read once. Pages are clean.",
    image: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
    seller: { name: "Riya Sharma", city: "Delhi" }
  },
  {
    id: 2,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "romantic",
    condition: "Very Good",
    price: 0,
    type: "donate",
    description: "Free book. Just want someone else to enjoy it.",
    image: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    seller: { name: "Aman Gupta", city: "Noida" }
  },
  {
    id: 3,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "fiction",
    condition: "Like New",
    price: 250,
    type: "sell",
    description: "Almost new condition.",
    image: "https://covers.openlibrary.org/b/id/7884866-L.jpg",
    seller: { name: "Sneha Verma", city: "Gurgaon" }
  },
  {
    id: 4,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "self-help",
    condition: "Good",
    price: 200,
    type: "sell",
    description: "Helpful self improvement book.",
    image: "https://covers.openlibrary.org/b/id/10521270-L.jpg",
    seller: { name: "Rahul Mehta", city: "Delhi" }
  },
  {
    id: 5,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "romantic",
    condition: "Very Good",
    price: 120,
    type: "sell",
    description: "Classic novel in great condition.",
    image: "https://covers.openlibrary.org/b/id/7352163-L.jpg",
    seller: { name: "Anjali Kapoor", city: "Faridabad" }
  },
  {
    id: 6,
    title: "1984",
    author: "George Orwell",
    genre: "fiction",
    condition: "Good",
    price: 100,
    type: "sell",
    description: "Dystopian classic.",
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    seller: { name: "Vikas Yadav", city: "Noida" }
  },
  {
    id: 7,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "fiction",
    condition: "Like New",
    price: 220,
    type: "sell",
    description: "Fantasy adventure book.",
    image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
    seller: { name: "Pooja Singh", city: "Delhi" }
  },
  {
    id: 8,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "fiction",
    condition: "Very Good",
    price: 130,
    type: "sell",
    description: "Famous American classic.",
    image: "https://covers.openlibrary.org/b/id/8225261-L.jpg",
    seller: { name: "Amit Chauhan", city: "Ghaziabad" }
  },
  {
    id: 9,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    genre: "self-help",
    condition: "Good",
    price: 140,
    type: "sell",
    description: "Motivational and business mindset book.",
    image: "https://covers.openlibrary.org/b/id/8231990-L.jpg",
    seller: { name: "Neha Gupta", city: "Delhi" }
  },
  {
    id: 10,
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    genre: "self-help",
    condition: "Like New",
    price: 210,
    type: "sell",
    description: "Finance and wealth mindset.",
    image: "https://covers.openlibrary.org/b/id/10110415-L.jpg",
    seller: { name: "Saurabh Jain", city: "Noida" }
  },
  {
    id: 11,
    title: "The Power of Habit",
    author: "Charles Duhigg",
    genre: "self-help",
    condition: "Good",
    price: 160,
    type: "sell",
    description: "Book about habits and behavior.",
    image: "https://covers.openlibrary.org/b/id/7100921-L.jpg",
    seller: { name: "Kunal Sharma", city: "Delhi" }
  },
  {
    id: 12,
    title: "Ikigai",
    author: "Hector Garcia",
    genre: "self-help",
    condition: "Very Good",
    price: 180,
    type: "sell",
    description: "Japanese concept of a happy life.",
    image: "https://covers.openlibrary.org/b/id/9251996-L.jpg",
    seller: { name: "Simran Kaur", city: "Gurgaon" }
  },
  {
    id: 13,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    genre: "self-help",
    condition: "Good",
    price: 170,
    type: "sell",
    description: "Popular self help book.",
    image: "https://covers.openlibrary.org/b/id/8370226-L.jpg",
    seller: { name: "Rohit Verma", city: "Delhi" }
  },
  {
    id: 14,
    title: "Little Women",
    author: "Louisa May Alcott",
    genre: "romantic",
    condition: "Very Good",
    price: 110,
    type: "sell",
    description: "Classic coming of age novel.",
    image: "https://covers.openlibrary.org/b/id/8097440-L.jpg",
    seller: { name: "Nidhi Sharma", city: "Noida" }
  },
  {
    id: 15,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "fiction",
    condition: "Good",
    price: 120,
    type: "sell",
    description: "Classic coming of age story.",
    image: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
    seller: { name: "Aditya Mishra", city: "Delhi" }
  }
]

export default Books